"""
Reference Gaussian sampler over the integers (samplerz) for Falcon, in
float64. (Modified) copy of the upstream Thomas Prest reference at
https://github.com/tprest/falcon.py, kept here as a runtime dependency
for `falcon_ref/test.py`. Production fxp code uses the deterministic
port at `fxp/samplerz_fxp.py` (bit-identical under shared
randomness modulo banker's-shift rounding).

Two split-and-sample modes are supported, switchable at module load time
or per call:

  ``floor`` (default, Falcon spec): ``s = floor(c)``, ``r = c − s ∈ [0, 1)``,
            bimodal extension ``z = b + (2b−1)·z₀`` for ``z₀ ∈ Z⁺``.
            Numerically unstable when c is near an integer (LTYZ
            paper 2024-1709 attack surface).

  ``round`` (LTYZ Algorithm 4 NewSamplerZ): ``s = round(c)`` (banker's,
            round-half-to-even via Python's built-in ``round``),
            ``r = c − s ∈ [−1/2, 1/2)``, bimodal extension
            ``z = (2b−1)·z₀`` for ``z₀ ∈ Z⁺``. Numerically unstable at
            half-integers — but those don't occur in Falcon under the
            paper's keygen restriction ``‖(g, −f)‖² odd``, so this shifts
            the round-off-sensitive locus out of harm's way.

Both modes use the same rejection formula
``x = (z − r)²·dss − z₀²·INV_2SIGMA2`` and the same berexp+approxexp.
The only differences are the s/r split convention, the bimodal extension,
and the base RCDT (different center). See ``scripts/generate_rcdt.py``
for how the two RCDTs are derived (Howe-Prest-Ricosset-Rossi 2019-1411
§5.2 rounding procedure, applied to the half-Gaussian centered at 0
resp. 1/2).
"""

# Importing dependencies
from math import floor

# Use high-quality randomness
# The "secrets" library could also work (Python >= 3.6)
from os import urandom


# Upper bound on all the values of sigma
MAX_SIGMA = 1.8205
INV_2SIGMA2 = 1 / (2 * (MAX_SIGMA ** 2))

# Precision of RCDT
RCDT_PREC = 72

# ln(2) and 1 / ln(2), with ln the natural logarithm
LN2 = 0.69314718056
ILN2 = 1.44269504089


# Default samplerz mode for module-level callers (samplerz can also be
# called with an explicit mode= keyword to override). "floor" reproduces
# the Falcon spec verbatim; "round" implements LTYZ's NewSamplerZ.
SAMPLERZ_MODE = "floor"


# RCDT_FLOOR: half-Gaussian centered at μ = 0, no halving D(0). Matches
# Falcon spec §3.9.3 Table 3.1 bit-for-bit (cf. scripts/generate_rcdt.py).
RCDT_FLOOR = [
    3024686241123004913666,
    1564742784480091954050,
    636254429462080897535,
    199560484645026482916,
    47667343854657281903,
    8595902006365044063,
    1163297957344668388,
    117656387352093658,
    8867391802663976,
    496969357462633,
    20680885154299,
    638331848991,
    14602316184,
    247426747,
    3104126,
    28824,
    198,
    1]

# RCDT_ROUND: half-Gaussian centered at μ = 1/2, D(0) halved. The
# distribution NewBaseSampler(LTYZ Algorithm 4) reads — generated by
# scripts/generate_rcdt.py with the same 2019-1411 §5.2 rounding rule
# (truncate then mass-conserve on the largest entry, here D(1)).
RCDT_ROUND = [
    3899470320143983480877,
    2253677994692660015228,
    1036552621035575352532,
    370887374867150348556,
    101649140428940578446,
    21115400469750986562,
    3300668784248344015,
    386323619417263643,
    33739318213646739,
    2193249886848467,
    105935861234397,
    3797090532647,
    100905148891,
    1986734192,
    28967961,
    312672,
    2496,
    14]

# Backwards-compat alias; pre-existing code that imports ``RCDT`` still
# works and gets the Falcon-spec table.
RCDT = RCDT_FLOOR


# C contains the coefficients of a polynomial that approximates exp(-x)
# More precisely, the value:
# (2 ** -63) * sum(C[12 - i] * (x ** i) for i in range(i))
# Should be very close to exp(-x).
# This polynomial is lifted from FACCT: https://doi.org/10.1109/TC.2019.2940949
C = [
    0x00000004741183A3,
    0x00000036548CFC06,
    0x0000024FDCBF140A,
    0x0000171D939DE045,
    0x0000D00CF58F6F84,
    0x000680681CF796E3,
    0x002D82D8305B0FEA,
    0x011111110E066FD0,
    0x0555555555070F00,
    0x155555555581FF00,
    0x400000000002B400,
    0x7FFFFFFFFFFF4800,
    0x8000000000000000]


def basesampler(randombytes=urandom, mode=None):
    """
    Sample z0 in {0, 1, ..., 18} with a distribution close to a
    half-Gaussian of parameter MAX_SIGMA, centered on 0 (mode="floor")
    or 1/2 (mode="round"). Takes as (optional) input the randomness
    source (default: urandom). When ``mode`` is None, falls back to the
    module-level ``SAMPLERZ_MODE``.
    """
    if mode is None:
        mode = SAMPLERZ_MODE
    rcdt = RCDT_FLOOR if mode == "floor" else RCDT_ROUND
    u = int.from_bytes(randombytes(RCDT_PREC >> 3), "little")

    z0 = 0
    for elt in rcdt:
        z0 += int(u < elt)
    return z0


def approxexp(x, ccs):
    """
    Compute an approximation of 2^63 * ccs * exp(-x).

    Input:
    - a floating-point number x
    - a scaling factor ccs
    Both inputs x and ccs MUST be positive.

    Output:
    - an integral approximation of 2^63 * ccs * exp(-x).
    """
    # y, z are always positive
    y = C[0]
    # Since z is positive, int is equivalent to floor
    z = int(x * (1 << 63))
    for elt in C[1:]:
        y = elt - ((z * y) >> 63)
    z = int(ccs * (1 << 63)) << 1
    y = (z * y) >> 63
    return y


def berexp(x, ccs, randombytes=urandom):
    """
    Return a single bit, equal to 1 with probability ~ ccs * exp(-x).
    Both inputs x and ccs MUST be positive.
    Also takes as (optional) input the randomness source (default: urandom).
    """
    s = int(x * ILN2)
    r = x - s * LN2
    s = min(s, 63)
    z = (approxexp(r, ccs) - 1) >> s
    for i in range(56, -8, -8):
        p = int.from_bytes(randombytes(1), "little")
        w = p - ((z >> i) & 0xFF)
        if w:
            break
    return (w < 0)


def samplerz(mu, sigma, sigmin, randombytes=urandom, mode=None):
    """
    Given floating-point values mu, sigma (and sigmin),
    output an integer z according to the discrete
    Gaussian distribution D_{Z, mu, sigma}.

    Input:
    - the center mu
    - the standard deviation sigma
    - a scaling factor sigmin
    - optional: the randomness source randombytes (default: urandom)
      randombytes(k) should output k pseudorandom bytes
    - optional: ``mode`` ∈ {"floor", "round"} selecting the s/r split
      convention. ``floor`` = Falcon spec; ``round`` = LTYZ NewSamplerZ
      (Algorithm 4 of paper 2024-1709). When None, uses the module-
      level ``SAMPLERZ_MODE``.
    The inputs MUST verify 1 < sigmin < sigma < MAX_SIGMA.

    Output:
    - a sample z from the distribution D_{Z, mu, sigma}.
    """
    if mode is None:
        mode = SAMPLERZ_MODE

    if mode == "floor":
        s = int(floor(mu))
    else:
        # Python 3 round() = round-half-to-even (banker's), matching ⌊·⌉
        # in LTYZ. Returns int, no precision loss for typical Falcon mu.
        s = round(mu)
    r = mu - s
    dss = 1 / (2 * sigma * sigma)
    ccs = sigmin / sigma

    while(1):
        # Sample z0 from a half-Gaussian (mode-specific RCDT).
        z0 = basesampler(randombytes=randombytes, mode=mode)
        # Bimodal extension: z = b + (2b−1)·z0 for floor (Falcon spec),
        # or z = (2b−1)·z0 for round (LTYZ Algorithm 4).
        b = int.from_bytes(randombytes(1), "little")
        b &= 1
        if mode == "floor":
            z = b + (2 * b - 1) * z0
            # Falcon classic rejection: x = (z − r)²·dss − z0²·INV_2SIGMA2.
            # The proxy distribution D_{Z⁺, σmax, 0} has rho ∝ exp(-z0²/(2σmax²)),
            # which is exactly cancelled by the +z0²/(2σmax²) accept factor,
            # leaving the desired Gaussian factor exp(-(z-r)²/(2σ²)).
            sigma_correction = z0 ** 2
        else:
            z = (2 * b - 1) * z0
            # LTYZ Algorithm 4 line 5: x = (z − r)²·dss − (z0² − z0)·INV_2SIGMA2.
            # The proxy is D_{Z⁺, σmax, 1/2} with halved D(0), whose rho ∝
            # exp(-(z0 − 1/2)²/(2σmax²)). The (z0² − z0)/(2σmax²) accept term
            # cancels exactly: -(z0 − 1/2)² + (z0² − z0) = -1/4 (constant in z0),
            # yielding the desired Gaussian factor exp(-(z-r)²/(2σ²)).
            sigma_correction = z0 ** 2 - z0
        x = ((z - r) ** 2) * dss
        x -= sigma_correction * INV_2SIGMA2
        if berexp(x, ccs, randombytes=randombytes):
            return z + s
